apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: be-ingress-deny
  namespace: url-shortener
spec:
  podSelector:
    matchLabels:
      tier: logic
  policyTypes:
    - Ingress
  ingress: []

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: be-ingress-fe
  namespace: url-shortener
spec:
  podSelector:
    matchLabels:
      tier: logic
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              tier: web
      ports:
        - protocol: TCP
          port: 8080
