apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-traffic-deny
  namespace: url-shortener
spec:
  podSelector:
    matchLabels:
      tier: data
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-ingress-be
  namespace: url-shortener
spec:
  podSelector:
    matchLabels:
      tier: data
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              tier: logic
      ports:
        - protocol: TCP
          port: 3306
