# Local docker compose
services:
  frontend:
    build:
      context: ./frontend
      args:
          NGINX_CONFIG: nginx.conf.local
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "127.0.0.1:${BACKEND_PORT}:8080"
    depends_on:
      - mysqldb
    environment:
      DBMS_URL: ${DBMS_URL}
      DBMS_USERNAME: ${DBMS_USERNAME}
      DBMS_PASSWORD: ${DBMS_PASSWORD}

  mysqldb:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  mysql:
