apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-fe
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
        tier: web
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              for i in $(seq 1 30); do
                nslookup url-be-service.url-shortener.svc.cluster.local && exit 0
                echo "waiting for backend..."
                sleep 2
              done
              echo "backend not ready, exiting..."
              exit 1
      containers:
        - image: localhost/url-shortener-frontend:latest
          name: url-fe
          envFrom:
            - configMapRef:
                name: url-fe-config
            - secretRef:
                name: url-fe-secret
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 5
            failureThreshold: 6  # 30 seconds max
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 5
