server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:url-shortener-be}
  datasource:
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    url: ${DBMS_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

jwt:
  signer-key: ${JWT_SIGNER_KEY:ZpVU2+KjVQEFSU6NgV9+2SRzhT5YuIsXMDgTbDcrf3Y7O+W/bYzhDwVzZSOviQwdnzGMK91zo6tAsoS+px3lkJluXeMLr0MnbhWAx7KelaI=}
  expiration-time: ${JWT_EXPIRATION_TIME:3600}
  refresh-time: ${JWT_REFRESH_TIME:86400}

url:
  length: ${URL_LENGTH:6}
  expiration-time: ${URL_EXPIRATION_TIME:7}

api:
  prefix: ${API_PREFIX:/api}
