# base/kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: url-shortener

resources:
  - namespace.yml
  - ingress.yml

  - backend/deployment.yml
  - backend/networkpolicy.yml
  - backend/service.yml

  - frontend/deployment.yml
  - frontend/networkpolicy.yml
  - frontend/service.yml

  - database/networkpolicy.yml
  - database/service.yml
  - database/statefulset.yml
