apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yml
  - secrets/backend.secret.yml
  - secrets/database.secret.yml
  - secrets/frontend.secret.yml
  - secrets/cert.secret.yml

patches:
  - path: ingress-patch.yml
    target:
      kind: Ingress
      name: url-ingress
